# Generated by Django 4.2.30 on 2026-04-30 21:37

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente'), ('SECRETARIA', 'Secretaria'), ('LABORATORIO', 'Laboratorio')], default='CLIENTE', max_length=20, verbose_name='Rol')),
                ('nombre_optica', models.CharField(blank=True, max_length=200, verbose_name='Nombre de Óptica')),
                ('ciudad_optica', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('ruc_optica', models.CharField(blank=True, max_length=20, verbose_name='RUC')),
                ('vendedor_optica', models.CharField(blank=True, max_length=100, verbose_name='Vendedor')),
                ('telefono_optica', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('clave', models.SlugField(unique=True, verbose_name='Clave única')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('dropdown', 'Desplegable')], max_length=20, verbose_name='Tipo')),
                ('categoria', models.CharField(choices=[('LENTE', 'Tipo de Lente'), ('CARACTERISTICAS', 'Características'), ('MONTAJE', 'Montaje')], max_length=30, verbose_name='Categoría')),
                ('requerido', models.BooleanField(default=False, verbose_name='Requerido')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('opciones', models.JSONField(blank=True, default=list, verbose_name='Opciones')),
                ('valores_que_muestran', models.JSONField(blank=True, default=list, help_text='Lista de valores del campo padre que muestran este campo', verbose_name='Valores que muestran este campo')),
                ('depende_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campos_dependientes', to='pedidos.campo', verbose_name='Depende de')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
                'ordering': ['categoria', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Número de Orden')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDO', 'Recibido'), ('PROCESANDO', 'Procesando'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('nombre_optica', models.CharField(max_length=200, verbose_name='Nombre de Óptica')),
                ('ciudad_optica', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('ruc_optica', models.CharField(max_length=20, verbose_name='RUC')),
                ('vendedor_optica', models.CharField(max_length=100, verbose_name='Vendedor')),
                ('telefono_optica', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('tipo_lente', models.CharField(blank=True, choices=[('MONOFOCAL', 'Monofocales'), ('PROGRESIVO', 'Progresivos'), ('ESPECIAL', 'Especiales'), ('BIFOCAL', 'Bifocales')], max_length=20, verbose_name='Tipo de Lente')),
                ('diseno_lente', models.CharField(blank=True, max_length=100, verbose_name='Diseño')),
                ('od_esfera', models.CharField(blank=True, max_length=10, verbose_name='OD Esfera')),
                ('od_cilindro', models.CharField(blank=True, max_length=10, verbose_name='OD Cilindro')),
                ('od_eje', models.CharField(blank=True, max_length=10, verbose_name='OD Eje')),
                ('od_dnp', models.CharField(blank=True, max_length=10, verbose_name='OD DNP')),
                ('od_altura', models.CharField(blank=True, max_length=10, verbose_name='OD Altura')),
                ('od_adicion', models.CharField(blank=True, max_length=10, verbose_name='OD Adición')),
                ('oi_esfera', models.CharField(blank=True, max_length=10, verbose_name='OI Esfera')),
                ('oi_cilindro', models.CharField(blank=True, max_length=10, verbose_name='OI Cilindro')),
                ('oi_eje', models.CharField(blank=True, max_length=10, verbose_name='OI Eje')),
                ('oi_dnp', models.CharField(blank=True, max_length=10, verbose_name='OI DNP')),
                ('oi_altura', models.CharField(blank=True, max_length=10, verbose_name='OI Altura')),
                ('oi_adicion', models.CharField(blank=True, max_length=10, verbose_name='OI Adición')),
                ('horizontal', models.CharField(blank=True, max_length=10, verbose_name='Horizontal')),
                ('vertical', models.CharField(blank=True, max_length=10, verbose_name='Vertical')),
                ('puente', models.CharField(blank=True, max_length=10, verbose_name='Puente')),
                ('distancia_mecanica', models.CharField(blank=True, max_length=10, verbose_name='Distancia Mecánica')),
                ('montura_descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción Montura')),
                ('montura_estado', models.CharField(blank=True, choices=[('NUEVA', 'Nueva'), ('EN_USO', 'En uso')], max_length=20, verbose_name='Estado Montura')),
                ('montura_foto', models.ImageField(blank=True, null=True, upload_to='monturas/', verbose_name='Foto Montura')),
                ('tipo_bisel', models.CharField(blank=True, choices=[('SIN_BISEL', 'Sin bisel'), ('COMPLETO', 'Completo'), ('SEMI_AIRE', 'Semi aire'), ('AIRE', 'Aire')], max_length=20, verbose_name='Tipo de Bisel')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcodes/', verbose_name='Código de Barras')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PedidoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.JSONField(verbose_name='Valor')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='pedidos.campo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Valor de Campo',
                'verbose_name_plural': 'Valores de Campos',
                'unique_together': {('pedido', 'campo')},
            },
        ),
    ]
