# Generated by Django 4.2.30 on 2026-05-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='material',
            field=models.CharField(blank=True, max_length=20, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tratamiento_antireflejo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Antireflejo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tratamiento_filtro_azul',
            field=models.BooleanField(default=False, verbose_name='Filtro Luz Azul'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tratamiento_fotosensible',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fotosensible'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tratamiento_transitions',
            field=models.BooleanField(default=False, verbose_name='Transitions'),
        ),
    ]
