# Generated by Django 4.2.30 on 2026-05-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_add_material_tratamientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='indice',
            field=models.CharField(blank=True, max_length=10, verbose_name='Índice'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('dropdown', 'Desplegable'), ('tarjetas', 'Tarjetas')], max_length=20, verbose_name='Tipo'),
        ),
    ]
